language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# travis ci 서버의 home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

# noti
notifications:
  email:
    recipients:
      - sorkehdcjf@gmail.com

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY #travisc settings 저장값
    secret_access_key: $AWS_SECRET_KEY #travisc settings 저장값
    bucket: donghcul-spring-webservice-deploy #S3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    wait-until-deployed: true
    on:
      repo: sah3122/spring-webservice #github 주소
      branch: master